services:
  - type: worker
    name: telegram-birthday-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -m bot.main
    envVars:
      - key: BOT_TOKEN
        fromSecret: true